### ISSUE TITLE
Inverted inner-border button skin

### ISSUE THREAD

**Issue by jakerichan** [ui-kit/ui-kit#25]
Currently in the quiz taker when text is inverted:
![screen shot 2015-09-15 at 3 40 00 pm](https://cloud.githubusercontent.com/assets/991316/9890910/17b31fd6-5bc0-11e5-99c8-85f7c9f19da7.png)

**Comment by jaydenanderson** [comment]
I think this is functioning as intended. The inner border is supposed to be the same color as the accent color.
