### ISSUE TITLE
disabled buttons still allow hover

### ISSUE THREAD

**Issue by jakerichan** [ui-kit/ui-kit#34]
![screen shot 2015-10-16 at 11 10 32 am](https://cloud.githubusercontent.com/assets/991316/10548278/b22f61ca-73f6-11e5-95ce-0c71dfc535e1.png)
Hovered:
![screen shot 2015-10-16 at 11 10 44 am](https://cloud.githubusercontent.com/assets/991316/10548277/b21d4b7a-73f6-11e5-8492-6c140e90bb65.png)

**Comment by jaydenanderson** [comment]
I'll fix this.

**Comment by mndvns** [comment]
i fixed this yesterday, just forgot to commit
https://github.com/ui-kit/ui-kit/commit/1c9564d6a111d90ae385ea0c88cb2de6fdf29c54

it's committed and pushed now
